name: Upload Output to S3
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # 원하는 브랜치 이름

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install awscli
          pip install httpx

      - name: Run Python script and upload output to S3
        run: |
          python script.py > backend-version-info.html
          aws s3 cp backend-version-info.html s3://gw-version-test-bucket/backend-version-info.html
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
